core:
  logging:
    version: 1
    formatters:
      formatter:
        format: "[%(levelname)s] %(name)s: %(message)s"
    handlers:
      console:
        class: "logging.StreamHandler"
        level: "DEBUG"
        formatter: "formatter"
        stream: "ext://sys.stderr"
    root:
      level: "DEBUG"
      handlers: ["console"]
window:
  backend: "glfw"
  glfw:
    vsync: true
renderer:
  backend: "opengl"
compute:
  power_preference: "high-performance"

